# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Torappu__BuildableType(object):
    NONE = 0
    MELEE = 1
    RANGED = 2
    ALL = 3


class Torappu__RarityRank(object):
    TIER_1 = 0
    TIER_2 = 1
    TIER_3 = 2
    TIER_4 = 3
    TIER_5 = 4
    TIER_6 = 5
    E_NUM = 6


class Torappu__ProfessionCategory(object):
    NONE = 0
    WARRIOR = 1
    SNIPER = 2
    TANK = 4
    MEDIC = 8
    SUPPORT = 16
    CASTER = 32
    SPECIAL = 64
    TOKEN = 128
    TRAP = 256
    PIONEER = 512


class Torappu__EvolvePhase(object):
    PHASE_0 = 0
    PHASE_1 = 1
    PHASE_2 = 2
    PHASE_3 = 3
    E_NUM = 4


class Torappu__ItemType(object):
    NONE = 0
    CHAR = 1
    CARD_EXP = 2
    MATERIAL = 3
    GOLD = 4
    EXP_PLAYER = 5
    TKT_TRY = 6
    TKT_RECRUIT = 7
    TKT_INST_FIN = 8
    TKT_GACHA = 9
    ACTIVITY_COIN = 10
    DIAMOND = 11
    DIAMOND_SHD = 12
    HGG_SHD = 13
    LGG_SHD = 14
    FURN = 15
    AP_GAMEPLAY = 16
    AP_BASE = 17
    SOCIAL_PT = 18
    CHAR_SKIN = 19
    TKT_GACHA_10 = 20
    TKT_GACHA_PRSV = 21
    AP_ITEM = 22
    AP_SUPPLY = 23
    RENAMING_CARD = 24
    RENAMING_CARD_2 = 25
    ET_STAGE = 26
    ACTIVITY_ITEM = 27
    VOUCHER_PICK = 28
    VOUCHER_CGACHA = 29
    VOUCHER_MGACHA = 30
    CRS_SHOP_COIN = 31
    CRS_RUNE_COIN = 32
    LMTGS_COIN = 33
    EPGS_COIN = 34
    LIMITED_TKT_GACHA_10 = 35
    LIMITED_FREE_GACHA = 36
    REP_COIN = 37
    ROGUELIKE = 38
    LINKAGE_TKT_GACHA_10 = 39
    VOUCHER_ELITE_II_5 = 40
    VOUCHER_ELITE_II_6 = 41
    VOUCHER_SKIN = 42
    RETRO_COIN = 43
    PLAYER_AVATAR = 44
    UNI_COLLECTION = 45
    VOUCHER_FULL_POTENTIAL = 46
    RL_COIN = 47
    RETURN_CREDIT = 48
    MEDAL = 49
    CHARM = 50
    HOME_BACKGROUND = 51
    EXTERMINATION_AGENT = 52
    OPTIONAL_VOUCHER_PICK = 53
    ACT_CART_COMPONENT = 54
    VOUCHER_LEVELMAX_6 = 55
    VOUCHER_LEVELMAX_5 = 56
    ACTIVITY_POTENTIAL = 57
    ITEM_PACK = 58
    SANDBOX = 59
    FAVOR_ADD_ITEM = 60
    CLASSIC_SHD = 61
    CLASSIC_TKT_GACHA = 62
    CLASSIC_TKT_GACHA_10 = 63
    LIMITED_BUFF = 64
    CLASSIC_FES_PICK_TIER_5 = 65
    CLASSIC_FES_PICK_TIER_6 = 66


class Torappu__TypeEnum(object):
    BUFF = 0
    CUSTOM = 1


class Torappu__AbnormalFlag(object):
    STUNNED = 0
    SP_RECOVER_STOPPED = 1
    TARGET_FREE = 2
    BLOCK_FREE = 3
    HIDDEN = 4
    INVINCIBLE = 5
    UNDEADABLE = 6
    HEAL_FREE = 7
    UNBALANCE_IMMUNE = 8
    INVISIBLE = 9
    UNUSED_PLACEHOLDER_1 = 10
    DISARMED = 11
    SILENCED = 12
    UNMOVABLE = 13
    UNUSED_PLACEHOLDER_2 = 14
    ALLY_TARGET_FREE = 15
    FROZEN = 16
    CAMOUFLAGE = 17
    FORCE_DISARMED = 18
    STUNNED_NO_AMPLIFY_DAMAGE = 19
    DISABLE_COMBAT = 20
    ELEMENT_FREE_ALL = 21
    UNMOVABLE_PRIVATE = 22
    COLD = 23
    SKILL_NOT_ACTIVATABLE = 24
    LEVITATE = 25
    DURANCE = 26
    NOT_WITHDRAWABLE = 27
    OUT_OF_GROUND = 28
    E_NUM = 29


class Torappu__AbnormalCombo(object):
    SLEEPING = 0
    SHELTERING = 1
    E_NUM = 2


class Torappu__AttributeType(object):
    MAX_HP = 0
    ATK = 1
    DEF = 2
    MAGIC_RESISTANCE = 3
    COST = 4
    BLOCK_CNT = 5
    MOVE_SPEED = 6
    ATTACK_SPEED = 7
    BASE_ATTACK_TIME = 8
    RESERVED_0 = 9
    RESERVED_1 = 10
    RESERVED_2 = 11
    RESERVED_3 = 12
    HP_RECOVERY_PER_SEC = 13
    SP_RECOVERY_PER_SEC = 14
    ABILITY_RANGE_FORWARD_EXTEND = 15
    MAX_DEPLOY_COUNT = 16
    DEF_PENETRATE = 17
    MAGIC_RESIST_PENETRATE = 18
    HP_RECOVERY_PER_SEC_BY_MAX_HP_RATIO = 19
    TAUNT_LEVEL = 20
    RESPAWN_TIME = 21
    MAX_DECK_STACK_CNT = 22
    MASS_LEVEL = 23
    BASE_FORCE_LEVEL = 24
    DEF_PENETRATE_FIXED = 25
    ONE_MINUS_STATUS_RESISTANCE = 26
    MAGIC_RESIST_PENETRATE_FIXED = 27
    MAX_EP = 28
    EP_RECOVERY_PER_SEC = 29
    SP_RECOVER_RATIO = 30
    E_NUM = 31


class Torappu__FormulaItemType(object):
    ADDITION = 0
    MULTIPLIER = 1
    FINAL_ADDITION = 2
    FINAL_SCALER = 3


class Torappu__UnlockCondition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__UnlockCondition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__UnlockCondition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__UnlockCondition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__UnlockCondition
    def Phase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__UnlockCondition
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Torappu__UnlockConditionStart(builder):
    builder.StartObject(2)

def Torappu__UnlockConditionAddPhase(builder, phase):
    builder.PrependInt32Slot(0, phase, 0)

def Torappu__UnlockConditionAddLevel(builder, level):
    builder.PrependInt32Slot(1, level, 0)

def Torappu__UnlockConditionEnd(builder):
    return builder.EndObject()



class Torappu__DataPair(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__DataPair()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__DataPair(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__DataPair
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__DataPair
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__DataPair
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__DataPair
    def ValueStr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Torappu__DataPairStart(builder):
    builder.StartObject(3)

def Torappu__DataPairAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def Torappu__DataPairAddValue(builder, value):
    builder.PrependFloat32Slot(1, value, 0.0)

def Torappu__DataPairAddValueStr(builder, valueStr):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(valueStr), 0)

def Torappu__DataPairEnd(builder):
    return builder.EndObject()



class Torappu__TraitData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__TraitData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__TraitData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__TraitData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__TraitData
    def UnlockCondition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__UnlockCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TraitData
    def RequiredPotentialRank(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__TraitData
    def Blackboard(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__DataPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TraitData
    def BlackboardLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__TraitData
    def BlackboardIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Torappu__TraitDataStart(builder):
    builder.StartObject(3)

def Torappu__TraitDataAddUnlockCondition(builder, unlockCondition):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(unlockCondition), 0)

def Torappu__TraitDataAddRequiredPotentialRank(builder, requiredPotentialRank):
    builder.PrependInt32Slot(1, requiredPotentialRank, 0)

def Torappu__TraitDataAddBlackboard(builder, blackboard):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(blackboard), 0)

def Torappu__TraitDataStartBlackboardVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__TraitDataEnd(builder):
    return builder.EndObject()



class Torappu__TraitDataBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__TraitDataBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__TraitDataBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__TraitDataBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__TraitDataBundle
    def Candidates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__TraitData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TraitDataBundle
    def CandidatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__TraitDataBundle
    def CandidatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Torappu__TraitDataBundleStart(builder):
    builder.StartObject(1)

def Torappu__TraitDataBundleAddCandidates(builder, candidates):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(candidates), 0)

def Torappu__TraitDataBundleStartCandidatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__TraitDataBundleEnd(builder):
    return builder.EndObject()



class Torappu__AttributesData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__AttributesData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__AttributesData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__AttributesData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__AttributesData
    def MaxHp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def Atk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def Def_(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def MagicResistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def Cost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def BlockCnt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def MoveSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def AttackSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def BaseAttackTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def RespawnTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def HpRecoveryPerSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def SpRecoveryPerSec(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributesData
    def MaxDeployCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def MaxDeckStackCnt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def TauntLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def MassLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def BaseForceLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributesData
    def StunImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__AttributesData
    def SilenceImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__AttributesData
    def SleepImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__AttributesData
    def FrozenImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__AttributesData
    def LevitateImmune(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Torappu__AttributesDataStart(builder):
    builder.StartObject(22)

def Torappu__AttributesDataAddMaxHp(builder, maxHp):
    builder.PrependInt32Slot(0, maxHp, 0)

def Torappu__AttributesDataAddAtk(builder, atk):
    builder.PrependInt32Slot(1, atk, 0)

def Torappu__AttributesDataAddDef_(builder, def_):
    builder.PrependInt32Slot(2, def_, 0)

def Torappu__AttributesDataAddMagicResistance(builder, magicResistance):
    builder.PrependFloat32Slot(3, magicResistance, 0.0)

def Torappu__AttributesDataAddCost(builder, cost):
    builder.PrependInt32Slot(4, cost, 0)

def Torappu__AttributesDataAddBlockCnt(builder, blockCnt):
    builder.PrependInt32Slot(5, blockCnt, 0)

def Torappu__AttributesDataAddMoveSpeed(builder, moveSpeed):
    builder.PrependFloat32Slot(6, moveSpeed, 0.0)

def Torappu__AttributesDataAddAttackSpeed(builder, attackSpeed):
    builder.PrependFloat32Slot(7, attackSpeed, 0.0)

def Torappu__AttributesDataAddBaseAttackTime(builder, baseAttackTime):
    builder.PrependFloat32Slot(8, baseAttackTime, 0.0)

def Torappu__AttributesDataAddRespawnTime(builder, respawnTime):
    builder.PrependInt32Slot(9, respawnTime, 0)

def Torappu__AttributesDataAddHpRecoveryPerSec(builder, hpRecoveryPerSec):
    builder.PrependFloat32Slot(10, hpRecoveryPerSec, 0.0)

def Torappu__AttributesDataAddSpRecoveryPerSec(builder, spRecoveryPerSec):
    builder.PrependFloat32Slot(11, spRecoveryPerSec, 0.0)

def Torappu__AttributesDataAddMaxDeployCount(builder, maxDeployCount):
    builder.PrependInt32Slot(12, maxDeployCount, 0)

def Torappu__AttributesDataAddMaxDeckStackCnt(builder, maxDeckStackCnt):
    builder.PrependInt32Slot(13, maxDeckStackCnt, 0)

def Torappu__AttributesDataAddTauntLevel(builder, tauntLevel):
    builder.PrependInt32Slot(14, tauntLevel, 0)

def Torappu__AttributesDataAddMassLevel(builder, massLevel):
    builder.PrependInt32Slot(15, massLevel, 0)

def Torappu__AttributesDataAddBaseForceLevel(builder, baseForceLevel):
    builder.PrependInt32Slot(16, baseForceLevel, 0)

def Torappu__AttributesDataAddStunImmune(builder, stunImmune):
    builder.PrependBoolSlot(17, stunImmune, 0)

def Torappu__AttributesDataAddSilenceImmune(builder, silenceImmune):
    builder.PrependBoolSlot(18, silenceImmune, 0)

def Torappu__AttributesDataAddSleepImmune(builder, sleepImmune):
    builder.PrependBoolSlot(19, sleepImmune, 0)

def Torappu__AttributesDataAddFrozenImmune(builder, frozenImmune):
    builder.PrependBoolSlot(20, frozenImmune, 0)

def Torappu__AttributesDataAddLevitateImmune(builder, levitateImmune):
    builder.PrependBoolSlot(21, levitateImmune, 0)

def Torappu__AttributesDataEnd(builder):
    return builder.EndObject()



class Torappu__KeyFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__KeyFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__KeyFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__KeyFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__KeyFrame
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__KeyFrame
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__AttributesData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Torappu__KeyFrameStart(builder):
    builder.StartObject(2)

def Torappu__KeyFrameAddLevel(builder, level):
    builder.PrependInt32Slot(0, level, 0)

def Torappu__KeyFrameAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def Torappu__KeyFrameEnd(builder):
    return builder.EndObject()



class Torappu__PhaseData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__PhaseData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__PhaseData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__PhaseData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__PhaseData
    def CharacterPrefabKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__PhaseData
    def RangeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__PhaseData
    def MaxLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__PhaseData
    def AttributesKeyFrames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__KeyFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__PhaseData
    def AttributesKeyFramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__PhaseData
    def AttributesKeyFramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Torappu__PhaseData
    def EvolveCost(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__ItemBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__PhaseData
    def EvolveCostLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__PhaseData
    def EvolveCostIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def Torappu__PhaseDataStart(builder):
    builder.StartObject(5)

def Torappu__PhaseDataAddCharacterPrefabKey(builder, characterPrefabKey):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(characterPrefabKey), 0)

def Torappu__PhaseDataAddRangeId(builder, rangeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rangeId), 0)

def Torappu__PhaseDataAddMaxLevel(builder, maxLevel):
    builder.PrependInt32Slot(2, maxLevel, 0)

def Torappu__PhaseDataAddAttributesKeyFrames(builder, attributesKeyFrames):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(attributesKeyFrames), 0)

def Torappu__PhaseDataStartAttributesKeyFramesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__PhaseDataAddEvolveCost(builder, evolveCost):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(evolveCost), 0)

def Torappu__PhaseDataStartEvolveCostVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__PhaseDataEnd(builder):
    return builder.EndObject()



class Torappu__ItemBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__ItemBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__ItemBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__ItemBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__ItemBundle
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__ItemBundle
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__ItemBundle
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Torappu__ItemBundleStart(builder):
    builder.StartObject(3)

def Torappu__ItemBundleAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def Torappu__ItemBundleAddCount(builder, count):
    builder.PrependInt32Slot(1, count, 0)

def Torappu__ItemBundleAddType(builder, type):
    builder.PrependInt32Slot(2, type, 0)

def Torappu__ItemBundleEnd(builder):
    return builder.EndObject()



class Torappu__SpecializeLevelData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__SpecializeLevelData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__SpecializeLevelData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__SpecializeLevelData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__SpecializeLevelData
    def UnlockCond(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__UnlockCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__SpecializeLevelData
    def LvlUpTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__SpecializeLevelData
    def LevelUpCost(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__ItemBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__SpecializeLevelData
    def LevelUpCostLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__SpecializeLevelData
    def LevelUpCostIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def Torappu__SpecializeLevelDataStart(builder):
    builder.StartObject(3)

def Torappu__SpecializeLevelDataAddUnlockCond(builder, unlockCond):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(unlockCond), 0)

def Torappu__SpecializeLevelDataAddLvlUpTime(builder, lvlUpTime):
    builder.PrependInt32Slot(1, lvlUpTime, 0)

def Torappu__SpecializeLevelDataAddLevelUpCost(builder, levelUpCost):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(levelUpCost), 0)

def Torappu__SpecializeLevelDataStartLevelUpCostVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__SpecializeLevelDataEnd(builder):
    return builder.EndObject()



class Torappu__MainSkill(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__MainSkill()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__MainSkill(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__MainSkill
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__MainSkill
    def SkillId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__MainSkill
    def OverridePrefabKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__MainSkill
    def OverrideTokenKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__MainSkill
    def LevelUpCostCond(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__SpecializeLevelData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__MainSkill
    def LevelUpCostCondLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__MainSkill
    def LevelUpCostCondIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Torappu__MainSkill
    def UnlockCond(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__UnlockCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Torappu__MainSkillStart(builder):
    builder.StartObject(5)

def Torappu__MainSkillAddSkillId(builder, skillId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(skillId), 0)

def Torappu__MainSkillAddOverridePrefabKey(builder, overridePrefabKey):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(overridePrefabKey), 0)

def Torappu__MainSkillAddOverrideTokenKey(builder, overrideTokenKey):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(overrideTokenKey), 0)

def Torappu__MainSkillAddLevelUpCostCond(builder, levelUpCostCond):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(levelUpCostCond), 0)

def Torappu__MainSkillStartLevelUpCostCondVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__MainSkillAddUnlockCond(builder, unlockCond):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(unlockCond), 0)

def Torappu__MainSkillEnd(builder):
    return builder.EndObject()



class Torappu__TalentData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__TalentData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__TalentData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__TalentData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__TalentData
    def UnlockCondition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__UnlockCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TalentData
    def RequiredPotentialRank(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__TalentData
    def PrefabKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__TalentData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__TalentData
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__TalentData
    def RangeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__TalentData
    def Blackboard(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__DataPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TalentData
    def BlackboardLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__TalentData
    def BlackboardIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def Torappu__TalentDataStart(builder):
    builder.StartObject(7)

def Torappu__TalentDataAddUnlockCondition(builder, unlockCondition):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(unlockCondition), 0)

def Torappu__TalentDataAddRequiredPotentialRank(builder, requiredPotentialRank):
    builder.PrependInt32Slot(1, requiredPotentialRank, 0)

def Torappu__TalentDataAddPrefabKey(builder, prefabKey):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(prefabKey), 0)

def Torappu__TalentDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def Torappu__TalentDataAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def Torappu__TalentDataAddRangeId(builder, rangeId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rangeId), 0)

def Torappu__TalentDataAddBlackboard(builder, blackboard):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(blackboard), 0)

def Torappu__TalentDataStartBlackboardVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__TalentDataEnd(builder):
    return builder.EndObject()



class Torappu__TalentDataBundle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__TalentDataBundle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__TalentDataBundle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__TalentDataBundle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__TalentDataBundle
    def Candidates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__TalentData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__TalentDataBundle
    def CandidatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__TalentDataBundle
    def CandidatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Torappu__TalentDataBundleStart(builder):
    builder.StartObject(1)

def Torappu__TalentDataBundleAddCandidates(builder, candidates):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(candidates), 0)

def Torappu__TalentDataBundleStartCandidatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__TalentDataBundleEnd(builder):
    return builder.EndObject()



class Torappu__AttributeModifier(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__AttributeModifier()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__AttributeModifier(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__AttributeModifier
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__AttributeModifier
    def AttributeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributeModifier
    def FormulaItem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__AttributeModifier
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Torappu__AttributeModifier
    def LoadFromBlackboard(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__AttributeModifier
    def FetchBaseValueFromSourceEntity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Torappu__AttributeModifierStart(builder):
    builder.StartObject(5)

def Torappu__AttributeModifierAddAttributeType(builder, attributeType):
    builder.PrependInt32Slot(0, attributeType, 0)

def Torappu__AttributeModifierAddFormulaItem(builder, formulaItem):
    builder.PrependInt32Slot(1, formulaItem, 0)

def Torappu__AttributeModifierAddValue(builder, value):
    builder.PrependFloat32Slot(2, value, 0.0)

def Torappu__AttributeModifierAddLoadFromBlackboard(builder, loadFromBlackboard):
    builder.PrependBoolSlot(3, loadFromBlackboard, 0)

def Torappu__AttributeModifierAddFetchBaseValueFromSourceEntity(builder, fetchBaseValueFromSourceEntity):
    builder.PrependBoolSlot(4, fetchBaseValueFromSourceEntity, 0)

def Torappu__AttributeModifierEnd(builder):
    return builder.EndObject()



class Torappu__AttributeModifierData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__AttributeModifierData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__AttributeModifierData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__AttributeModifierData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__AttributeModifierData
    def AbnormalFlags(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Torappu__AttributeModifierData
    def AbnormalFlagsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalFlagsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalFlagsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Torappu__AttributeModifierData
    def AbnormalImmunes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Torappu__AttributeModifierData
    def AbnormalImmunesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalImmunesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalImmunesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Torappu__AttributeModifierData
    def AbnormalAntis(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Torappu__AttributeModifierData
    def AbnormalAntisAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalAntisLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalAntisIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Torappu__AttributeModifierData
    def AbnormalCombos(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Torappu__AttributeModifierData
    def AbnormalCombosAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalCombosLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalCombosIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Torappu__AttributeModifierData
    def AbnormalComboImmunes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Torappu__AttributeModifierData
    def AbnormalComboImmunesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalComboImmunesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AbnormalComboImmunesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Torappu__AttributeModifierData
    def AttributeModifiers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__AttributeModifier()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__AttributeModifierData
    def AttributeModifiersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__AttributeModifierData
    def AttributeModifiersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def Torappu__AttributeModifierDataStart(builder):
    builder.StartObject(6)

def Torappu__AttributeModifierDataAddAbnormalFlags(builder, abnormalFlags):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(abnormalFlags), 0)

def Torappu__AttributeModifierDataStartAbnormalFlagsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataAddAbnormalImmunes(builder, abnormalImmunes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(abnormalImmunes), 0)

def Torappu__AttributeModifierDataStartAbnormalImmunesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataAddAbnormalAntis(builder, abnormalAntis):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(abnormalAntis), 0)

def Torappu__AttributeModifierDataStartAbnormalAntisVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataAddAbnormalCombos(builder, abnormalCombos):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(abnormalCombos), 0)

def Torappu__AttributeModifierDataStartAbnormalCombosVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataAddAbnormalComboImmunes(builder, abnormalComboImmunes):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(abnormalComboImmunes), 0)

def Torappu__AttributeModifierDataStartAbnormalComboImmunesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataAddAttributeModifiers(builder, attributeModifiers):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(attributeModifiers), 0)

def Torappu__AttributeModifierDataStartAttributeModifiersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__AttributeModifierDataEnd(builder):
    return builder.EndObject()



class Torappu__ExternalBuff(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__ExternalBuff()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__ExternalBuff(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__ExternalBuff
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__ExternalBuff
    def Attributes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__AttributeModifierData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Torappu__ExternalBuffStart(builder):
    builder.StartObject(1)

def Torappu__ExternalBuffAddAttributes(builder, attributes):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(attributes), 0)

def Torappu__ExternalBuffEnd(builder):
    return builder.EndObject()



class Torappu__PotentialRank(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__PotentialRank()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__PotentialRank(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__PotentialRank
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__PotentialRank
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__PotentialRank
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__PotentialRank
    def Buff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__ExternalBuff()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__PotentialRank
    def EquivalentCost(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__ItemBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__PotentialRank
    def EquivalentCostLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__PotentialRank
    def EquivalentCostIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def Torappu__PotentialRankStart(builder):
    builder.StartObject(4)

def Torappu__PotentialRankAddType(builder, type):
    builder.PrependInt32Slot(0, type, 0)

def Torappu__PotentialRankAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def Torappu__PotentialRankAddBuff(builder, buff):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(buff), 0)

def Torappu__PotentialRankAddEquivalentCost(builder, equivalentCost):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(equivalentCost), 0)

def Torappu__PotentialRankStartEquivalentCostVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__PotentialRankEnd(builder):
    return builder.EndObject()



class Torappu__SkillLevelCost(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__SkillLevelCost()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__SkillLevelCost(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__SkillLevelCost
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__SkillLevelCost
    def UnlockCond(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__UnlockCondition()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__SkillLevelCost
    def LvlUpCost(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__ItemBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__SkillLevelCost
    def LvlUpCostLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__SkillLevelCost
    def LvlUpCostIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Torappu__SkillLevelCostStart(builder):
    builder.StartObject(2)

def Torappu__SkillLevelCostAddUnlockCond(builder, unlockCond):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(unlockCond), 0)

def Torappu__SkillLevelCostAddLvlUpCost(builder, lvlUpCost):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(lvlUpCost), 0)

def Torappu__SkillLevelCostStartLvlUpCostVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__SkillLevelCostEnd(builder):
    return builder.EndObject()



class Torappu__CharacterData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Torappu__CharacterData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorappu__CharacterData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Torappu__CharacterData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Torappu__CharacterData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def CanUseGeneralPotentialItem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__CharacterData
    def CanUseActivityPotentialItem(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__CharacterData
    def PotentialItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def ActivityPotentialItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def ClassicPotentialItemId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def NationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def TeamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def DisplayNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def TokenKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def Appellation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__CharacterData
    def TagList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Torappu__CharacterData
    def TagListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def TagListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # Torappu__CharacterData
    def ItemUsage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def ItemDesc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def ItemObtainApproach(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def IsNotObtainable(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__CharacterData
    def IsSpChar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Torappu__CharacterData
    def MaxPotentialLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__CharacterData
    def Rarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__CharacterData
    def Profession(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Torappu__CharacterData
    def SubProfessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Torappu__CharacterData
    def Trait(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__TraitDataBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def Phases(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__PhaseData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def PhasesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def PhasesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

    # Torappu__CharacterData
    def Skills(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__MainSkill()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def SkillsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def SkillsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        return o == 0

    # Torappu__CharacterData
    def Talents(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__TalentDataBundle()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def TalentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def TalentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        return o == 0

    # Torappu__CharacterData
    def PotentialRanks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__PotentialRank()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def PotentialRanksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def PotentialRanksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        return o == 0

    # Torappu__CharacterData
    def FavorKeyFrames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__KeyFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def FavorKeyFramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def FavorKeyFramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        return o == 0

    # Torappu__CharacterData
    def AllSkillLvlup(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Torappu__SkillLevelCost()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Torappu__CharacterData
    def AllSkillLvlupLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Torappu__CharacterData
    def AllSkillLvlupIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        return o == 0

def Torappu__CharacterDataStart(builder):
    builder.StartObject(31)

def Torappu__CharacterDataAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def Torappu__CharacterDataAddDescription(builder, description):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)

def Torappu__CharacterDataAddCanUseGeneralPotentialItem(builder, canUseGeneralPotentialItem):
    builder.PrependBoolSlot(2, canUseGeneralPotentialItem, 0)

def Torappu__CharacterDataAddCanUseActivityPotentialItem(builder, canUseActivityPotentialItem):
    builder.PrependBoolSlot(3, canUseActivityPotentialItem, 0)

def Torappu__CharacterDataAddPotentialItemId(builder, potentialItemId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(potentialItemId), 0)

def Torappu__CharacterDataAddActivityPotentialItemId(builder, activityPotentialItemId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(activityPotentialItemId), 0)

def Torappu__CharacterDataAddClassicPotentialItemId(builder, classicPotentialItemId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(classicPotentialItemId), 0)

def Torappu__CharacterDataAddNationId(builder, nationId):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(nationId), 0)

def Torappu__CharacterDataAddGroupId(builder, groupId):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(groupId), 0)

def Torappu__CharacterDataAddTeamId(builder, teamId):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(teamId), 0)

def Torappu__CharacterDataAddDisplayNumber(builder, displayNumber):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(displayNumber), 0)

def Torappu__CharacterDataAddTokenKey(builder, tokenKey):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(tokenKey), 0)

def Torappu__CharacterDataAddAppellation(builder, appellation):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(appellation), 0)

def Torappu__CharacterDataAddPosition(builder, position):
    builder.PrependInt32Slot(13, position, 0)

def Torappu__CharacterDataAddTagList(builder, tagList):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(tagList), 0)

def Torappu__CharacterDataStartTagListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddItemUsage(builder, itemUsage):
    builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(itemUsage), 0)

def Torappu__CharacterDataAddItemDesc(builder, itemDesc):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(itemDesc), 0)

def Torappu__CharacterDataAddItemObtainApproach(builder, itemObtainApproach):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(itemObtainApproach), 0)

def Torappu__CharacterDataAddIsNotObtainable(builder, isNotObtainable):
    builder.PrependBoolSlot(18, isNotObtainable, 0)

def Torappu__CharacterDataAddIsSpChar(builder, isSpChar):
    builder.PrependBoolSlot(19, isSpChar, 0)

def Torappu__CharacterDataAddMaxPotentialLevel(builder, maxPotentialLevel):
    builder.PrependInt32Slot(20, maxPotentialLevel, 0)

def Torappu__CharacterDataAddRarity(builder, rarity):
    builder.PrependInt32Slot(21, rarity, 0)

def Torappu__CharacterDataAddProfession(builder, profession):
    builder.PrependInt32Slot(22, profession, 0)

def Torappu__CharacterDataAddSubProfessionId(builder, subProfessionId):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(subProfessionId), 0)

def Torappu__CharacterDataAddTrait(builder, trait):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(trait), 0)

def Torappu__CharacterDataAddPhases(builder, phases):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(phases), 0)

def Torappu__CharacterDataStartPhasesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddSkills(builder, skills):
    builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(skills), 0)

def Torappu__CharacterDataStartSkillsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddTalents(builder, talents):
    builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(talents), 0)

def Torappu__CharacterDataStartTalentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddPotentialRanks(builder, potentialRanks):
    builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(potentialRanks), 0)

def Torappu__CharacterDataStartPotentialRanksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddFavorKeyFrames(builder, favorKeyFrames):
    builder.PrependUOffsetTRelativeSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(favorKeyFrames), 0)

def Torappu__CharacterDataStartFavorKeyFramesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataAddAllSkillLvlup(builder, allSkillLvlup):
    builder.PrependUOffsetTRelativeSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(allSkillLvlup), 0)

def Torappu__CharacterDataStartAllSkillLvlupVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def Torappu__CharacterDataEnd(builder):
    return builder.EndObject()



class KV_Torappu__CharacterData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KV_Torappu__CharacterData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKV_Torappu__CharacterData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KV_Torappu__CharacterData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KV_Torappu__CharacterData
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KV_Torappu__CharacterData
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Torappu__CharacterData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def KV_Torappu__CharacterDataStart(builder):
    builder.StartObject(2)

def KV_Torappu__CharacterDataAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def KV_Torappu__CharacterDataAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def KV_Torappu__CharacterDataEnd(builder):
    return builder.EndObject()



class character_table(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = character_table()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAscharacter_table(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # character_table
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # character_table
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = KV_Torappu__CharacterData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # character_table
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # character_table
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def character_tableStart(builder):
    builder.StartObject(1)

def character_tableAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def character_tableStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def character_tableEnd(builder):
    return builder.EndObject()

ROOT_TYPE = character_table
